# CMPT 742 Practices for Visual Computing 1

In [6]:
"""Q1"""

# Todo 1: Define a function to calculate the volume of a sphere
def calc_volume(r):
    """Returns the volume of a sphere with radius r."""
    assert r > 0, "radius should be greater than 0"
    volume = 0
    volume = 4 / 3 * 3.14 * (r ** 3) 
    return volume

# Todo 2: Define a function to calculate the surface area of a sphere
def calc_surface_area(r):
    """Returns the surface area of a sphere with radius r."""
    surface_area = 0
    surface_area = 4 * 3.14 * (r ** 2)
    return surface_area

radius = 2

# Todo 3: Call the functions and print the results

In [7]:
print(calc_volume(radius))
print(calc_surface_area(radius))

33.49333333333333
50.24


In [9]:
"""Q2"""

iterations = 1000000

# approximate the value of pi
pi = 0
def vol_of_sphere(iter):
    sum = 0
    for i in range(1, iter+1):
        sum += 1 / (iter**2)
    return ((sum * 6) ** 0.5) / 2

pi = vol_of_sphere(iterations)

print("Pi is approximately", pi, "after", iterations, "iterations")

Pi is approximately 0.0012247448713968868 after 1000000 iterations


In [18]:
"""Q3"""

import random

# Todo 1: Set a seed
random.seed = 10    

# Todo 2: weighted_sum using for loop
def weighted_sum_1(weights, values):
    """Calculate weighted sum using for loop"""
    # check the lengths are the same
    assert len(weights) == len(values), "the length of weights does not equal to the length of values"
    sum = 0
    for i in range(len(weights)):
        sum += weights[i] * values[i]
    return sum

# Todo 3: weighted_sum using list comprehension
def weighted_sum_2(weights, values):
    """Calculate weighted sum using list comprehension"""
    assert len(weights) == len(values), "the length of weights does not equal to the length of values"
    return sum([weights[i] * values[i] for i in range(len(weights))])

# Define main function
def main():
    # Todo 4: Generate random weights and values
    weights = [round(random.uniform(1, 0), 2) for _ in range(100)]
    values = [round(random.uniform(1, 0), 2) for _ in range(100)]
    
    print("weighted_sum_1:", weighted_sum_1(weights, values))
    print("weighted_sum_1:", weighted_sum_2(weights, values))

if __name__ == "__main__":
    main()

weighted_sum_1: 24.341600000000003
weighted_sum_1: 24.341600000000003


In [3]:
"""Q4"""

students_grades = {
    "std1": {"a1": 95, "a2": 90, "a3": 85, "a4": 90},
    "std2": {"a1": 90, "a2": 85, "a3": 80, "a4": 85},
    "std3": {"a1": 85, "a2": 80, "a3": 100, "a4": 80},
    "std4": {"a1": 90, "a2": 75, "a3": 70, "a4": 95}
}

# Todo 1: Define a function to add average to each student's grades
def add_avg(grades):
    """Add average to each student's' grades"""
    assert grades, "grades is empty"
    for std in grades:
        grades[std]["avg"] = sum(grades[std].values()) / len(std)
    return grades

print(add_avg(students_grades))

# Todo 2: Define a function to calculate the average of a student's grades for std1
def avg_std1(grades):
    assert grades, "grades is empty"
    assert grades['std1'], "std1 is not in the dictionary"
    return sum(grades['std1'].values()) / len(grades['std1'])

print((avg_std1(students_grades)))

{'std1': {'a1': 95, 'a2': 90, 'a3': 85, 'a4': 90, 'avg': 90.0}, 'std2': {'a1': 90, 'a2': 85, 'a3': 80, 'a4': 85, 'avg': 85.0}, 'std3': {'a1': 85, 'a2': 80, 'a3': 100, 'a4': 80, 'avg': 86.25}, 'std4': {'a1': 90, 'a2': 75, 'a3': 70, 'a4': 95, 'avg': 82.5}}
90.0


In [16]:
"""Q5"""
import csv 

# Todo 1: Write student grades in CSV format
with open("grades.csv", "w") as f:
    fieldnames = list(students_grades["std1"].keys())
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()

    for row_id, row_data in students_grades.items():
        row_data["std_number"] = row_id
        writer.writerow(row_data)

# Todo 2: Write student grades in JSON format
import json
json_file_path = "grades.json"
# Write the data to the JSON file
with open(json_file_path, "w") as json_file:
    json.dump(students_grades, json_file, indent=4)

In [29]:
"""Q6"""

# Todo 1: Create a specified class with methods
class Student:
    def __init__(self, student_id, name, age, sex, course_name):
        self.student_id = student_id
        self.name = name
        self.age = age
        self.sex = sex
        self.course_name = course_name
        self.courses = []
    def add_course(self, course_name, gpa):
        self.courses.append({"course_name": course_name, "gpa": gpa})
        return self.courses
    def export_info(self):
        with open("courses.txt", "w") as file:
            file.write(f"Student ID: {self.student_id}\n")
            file.write(f"Name: {self.name}\n")
            file.write(f"Age: {self.age}\n")
            file.write(f"Sex: {self.sex}\n")
            file.write(f"Course Name: {self.course_name}\n")
            file.write("Courses and GPAs:\n")
            for course in self.courses:
                file.write(f"  Course: {course['course_name']}, GPA: {course['gpa']}\n")
            
# Initialize Student object
student1 = Student("amx333", "Alice", 21, "Female", "Computer Science")

# Add courses and grades
student1.add_course("Math", 3.5)
student1.add_course("Programming", 4.0)
student1.add_course("Algorithms", 3.7)

# Export student info to a text file
student1.export_info()

In [38]:
"""Q7"""

import numpy as np

# Todo 1: Create required numpy arrays
A = np.array([
    [1, 2, 2],
    [1, 0, 1]
    ])
B = np.array([
    [3, 1],
    [1, 1],
    [1, 0]
])
print(A)
print(A.shape)
print(np.ndim(A))
print(B)
print(B.shape)
print(np.ndim(B))

# Todo 2: Calculated required multiplication
print(A @ B) # dot product
print(B @ A)

[[1 2 2]
 [1 0 1]]
(2, 3)
2
[[3 1]
 [1 1]
 [1 0]]
(3, 2)
2
[[7 3]
 [4 1]]
[[4 6 7]
 [2 2 3]
 [1 2 2]]


In [48]:
"""Q8"""

import numpy as np
import random

# Todo 1: Create required numpy array
A = np.random.randn(6, 6)

# Todo 2: Manipulate the array into desired format using array slicing
A[0:2, :] = 0
A[:, 0:2] = 0
A[4:6, :] = 0
A[:, 4:6] = 0
A

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.13796381, -2.13315754,  0.        ,
         0.        ],
       [ 0.        ,  0.        , -1.27612863, -2.06150385,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ]])

In [67]:
import random
import time
# from q3 import weighted_sum_2 as weighted_sum_list

random.seed(123)

weights = [random.uniform(0, 1) for i in range(1000000)]
values = [random.uniform(0, 1) for i in range(1000000)]

# Todo 1: Perform the weighted average using NumPy
a = np.average(values, weights = weights)
print("the weighted average using NumPy is:", a)

# Todo 2: Measure the time taken to perform the weighted average using NumPy vs list comprehension
# timer decorator
def timer(func):
    def inner(*args, **kwargs):
        start = time.time()
        result = func(*args, **kwargs)
        end = time.time()
        running_time = end - start
        print("the reuslt of ", func, "is", result)
        print(f"Running time: {running_time:.5f} seconds") 
        return result
    return inner

@timer
def weighted_sum_2(weights, values):
    """Calculate weighted sum using list comprehension"""
    assert len(weights) == len(values), "the length of weights does not equal to the length of values"
    return sum([weights[i] * values[i] for i in range(len(weights))]) / len(values)

@timer
def numpy_weighted_sum(weights, values):
    assert len(weights) == len(values), "the length of weights does not equal to the length of values"
    return np.average(values, weights = weights)

# print("Using list comprehension:")
result_list_comp = weighted_sum_2(weights, values)

# print("Using NumPy:")
result_numpy = numpy_weighted_sum(weights, values)


the weighted average using NumPy is: 0.5002639579804737
the reuslt of  <function weighted_sum_2 at 0x105972ca0> is 0.2501762748298525
Running time: 0.03354 seconds
the reuslt of  <function numpy_weighted_sum at 0x105972e80> is 0.5002639579804737
Running time: 0.04251 seconds


# n is # of control point

# find Bezier Curve with (0, 0), (1, 1) and (2, 0) as control points.

C(0) = (0, 0) * B0,2(u) + (1, 1) * B1,2(u) + (2, 0) * B2,2(u)

B0,2(u) = (1-u)**2
B1,2(u) = 2(1-u)u
B2,2(u) = u**2

c(u) = (0, 0) * (1-u)**2 + (1, 1) * 2(1-u)u + (2, 0) * u**2
c(u) = (2u, 2u-2u**2)
c(0.5) = (1, 1-2*1/4) = (1, 0.5)
